function riskGraph=createGraph(SPMP,SPMPNames,inputParameters,intermediateNodes,risk,LOIMethod)
%PLOTGRAPH Summary of this function goes here
%   Detailed explanation goes here
    riskGraph=digraph;
    shortNames={"PML";"SCA";"AML";"PRM";"PR";"PRM-PR";"NTA";"NTS";"SPI";"AV";"NT-AV";"AC";"AR";"AML-AC";"AML-AR";"EM";"AL";"VI";"VC";"VA"; ...
               "OAF";"ISL";"OAF-VA";"ISL-VC";"S";"AS";"ACSRL";"OAB";"OAB-AR";"OAB-AC";"OAB-AR-AC";"SAB";"SAB-UI";'UI'};
    fullNames=['Password management level';'Strong customer authentication'; 'Access management level'; 'Permissions'; 'Privilege Requirement'; ...
               'Permissions + Privilege Requirement'; 'Network access type'; 'Network security type'; 'Security Parameters Index';'Attack Vector'; ...
               'Network type + attack vector'; 'Attack complexity'; 'Attack requirements'; "Access management level + Attack complexity"; ...
               'Access management level + Attack requirements'; 'Exploit maturity'; 'Attack likelihood'; 'Vulnerable System Integrity'; ...
               'Vulnerable System Confidentiality'; 'Vulnerable System Availability'; 'Object access frequency';'Information sensitivity level'; ...
               'Object access frequency + Vulnerable System Availability'; 'Information sensitivity level + Vulnerable System Confidentiality'; ...
               'Safety';'Attack severity';'Access control system risk level';'Object Anomaly Behavior';'Object Anomaly Behavior + Attack requirements';...
               'Object Anomaly Behavior + Attack complexity';'Object Anomaly Behavior + Attack requirements + Attack complexity';'Subject Anomaly Behavior';...
               'Subject Anomaly Behavior + User Interaction';'User Interaction'];
    controllable=[1;1;1;1;0;1;1;1;1;0;1;0;0;1;1;0;1;0;0;0;1;1;1;1;0;1;1;1;1;1;1;1;1;0];
    NodeProps = table(keys(SPMP), values(SPMP),SPMPNames',[1;1;1;1;1;1;1;1;1],1-values(SPMP), 'VariableNames', {'Name' 'Value' 'FullName' 'Controllable' 'InvertedValue'});
    sourceNodes=["RAL","mPA", "ALD", "MPA", "EPH","ALT", "MPL","PCR", "SPE","SCA","PML","PRM","PR","SPI","NTA","NTS","SPI","AV","AML","AC",...
        "AML","AR","AML-AC","AML-AR","NT-AV","PRM-PR","EM","OAF","VA","ISL","VC","VI","ISL-VC","OAF-VA","S","AL","AS","OAB","AR","OAB","AC","OAB-AC","OAB-AR","SAB","UI",...
        "SAB-UI","OAB-AR-AC"];
    targetNodes=["PML","PML","PML","PML","PML","PML","PML","PML","PML","AML","AML","PRM-PR","PRM-PR","PRM-PR","NT-AV","NT-AV","NT-AV","NT-AV",...
        "AML-AC","AML-AC","AML-AR","AML-AR","AL","AL","AL","AL","AL","OAF-VA","OAF-VA","ISL-VC","ISL-VC","AS","AS","AS","AS","ACSRL","ACSRL","OAB-AR","OAB-AR","OAB-AC","OAB-AC",...
        "OAB-AR-AC","OAB-AR-AC","SAB-UI","SAB-UI","AL","AL"];
    %tmp=[sourceNodes;targetNodes "0"];
    NodeProps=[NodeProps;...
               table(shortNames, ...
               [inputParameters("PML");inputParameters("SCA");intermediateNodes("AML"); ...
               inputParameters("PRM");inputParameters("PR");intermediateNodes("coefPRM_PR");inputParameters("NTA"); ...
               inputParameters("NTS");inputParameters("SPI");inputParameters("AV"); ...
               intermediateNodes("coefNT_AV");inputParameters("AC");inputParameters("AR");intermediateNodes("coefAML_AC"); ...
               intermediateNodes("coefAML_AR");inputParameters("EM");intermediateNodes("AL");inputParameters("VI");inputParameters("VC");inputParameters("VA"); ...
               inputParameters("OAF");inputParameters("ISL");intermediateNodes("coefOAF_VA"); ...
               intermediateNodes("coefISL_VC");inputParameters("S");intermediateNodes("AS");risk;inputParameters("OAB");intermediateNodes("coefOAB_AR");...
               intermediateNodes("coefOAB_AC");intermediateNodes("coefOAB_AR_AC");inputParameters("SAB");intermediateNodes("coefSAB_UI");inputParameters("UI")], ...
               fullNames,controllable, ...
               [1-inputParameters("PML")/10;1-inputParameters("SCA")/10;1-intermediateNodes("AML"); ...
               inputParameters("PRM");1-inputParameters("PR");intermediateNodes("coefPRM_PR");1-inputParameters("NTA"); ...
               1-inputParameters("NTS");1-inputParameters("SPI");1-inputParameters("AV"); ...
               intermediateNodes("coefNT_AV");1-inputParameters("AC");1-inputParameters("AR");intermediateNodes("coefAML_AC"); ...
               intermediateNodes("coefAML_AR");inputParameters("EM");intermediateNodes("AL");inputParameters("VI");inputParameters("VC");inputParameters("VA"); ...
               inputParameters("OAF");inputParameters("ISL");intermediateNodes("coefOAF_VA"); ...
               intermediateNodes("coefISL_VC");inputParameters("S");intermediateNodes("AS");risk;inputParameters("OAB");intermediateNodes("coefOAB_AR");...
               intermediateNodes("coefOAB_AC");intermediateNodes("coefOAB_AR_AC");inputParameters("SAB");intermediateNodes("coefSAB_UI");inputParameters("UI")],...
               'VariableNames', {'Name' 'Value' 'FullName' 'Controllable' 'InvertedValue'})
    ];
    if LOIMethod=="direct"
        sourceNodes=[sourceNodes, "LOI"];
        targetNodes=[targetNodes,"AS"];
        NodeProps=[NodeProps;...
               table({"LOI"},[inputParameters("LOI")],"Level of influence",1,[inputParameters("LOI")],'VariableNames', {'Name' 'Value' 'FullName' 'Controllable' 'InvertedValue'})];
    end
    % Mark missing nodes; rendering handled in plotGraph
    NodeProps.IsMissing = NodeProps.Value == -1;
    riskGraph = addnode(riskGraph, NodeProps);
    riskGraph = addedge(riskGraph, sourceNodes,targetNodes);
end

