featureNames=["PML","SCA","SAB",...
    "PRM","OVL","OAF","ISL",...
    "LODI","PR","AV","EM",...
    "NTA","NTS","OAB"];

fis1 = createFIS("fis_AML", repmat([0;1],1,2), ...
    featureNames(1:2),"AML");
fis2 = createFIS("fis_AL",repmat([0;1],1,6), ...
    {"AML",featureNames(4),featureNames(9),featureNames(10),featureNames(12),featureNames(13)},"AL");
fis3 = createFIS("fis_ASL",repmat([0;1],1,4), ...
    {featureNames(5),featureNames(6),featureNames(7),featureNames(8)},"ASL");
fis4 = createFIS("fis_ACSRL",repmat([0;1],1,2), ...
    {"AL","ASL"},"ACSRL");
fis5 = createFIS("fis_DACSRL",repmat([0;1],1,3), ...
    {featureNames(3),featureNames(14),"ACSRL"},"DACSRL");
fis = [fis1 fis2 fis3 fis4 fis5];

connections = [...
    "fis_AML/AML" "fis_AL/AML"; ...
    "fis_AL/AL" "fis_ACSRL/AL"; ...
    "fis_ASL/ASL" "fis_ACSRL/ASL"; ...
    "fis_ACSRL/ACSRL" "fis_DACSRL/ACSRL"; ...
    ];
fisT = fistree(fis,connections);

h = figure;
plotfis(fisT,Legend="on")
h.Position(3:4) = [0.95*h.Position(3) 0.85*h.Position(4)];