function plotGUI(Risks,usersNames,objectsNames,fig,defaultRiskThreshold,preferredVisibleUserIdx)
%PLOTGUI Summary of this function goes here
%   Detailed explanation goes here
    fprintf('Risk GUI plotGUI path: %s\n', mfilename('fullpath'));
    if nargin < 5 || isempty(defaultRiskThreshold)
        defaultRiskThreshold = 0;
    end
    if nargin < 6
        preferredVisibleUserIdx = [];
    end
    [defaultRiskThreshold, thresholdSliderValue, thresholdText] = normalizeDefaultRiskThreshold(defaultRiskThreshold);
    usersNames = string(usersNames(:));
    objectsNames = string(objectsNames(:));
    graphList = cellstr(["All"; string(usersNames(:)); string(objectsNames(:))]);
    ax = axes('Parent', fig, ...
        'Units', 'pixels', ...
        'Position', [230 120 900 480], ...
        'Tag', 'RiskPlotAxes');
    guidata(fig, ax);
    lb = uicontrol(fig, ...
        'Style', 'listbox', ...
        'Position', [20 20 140 600], ...
        'String', graphList, ...
        'Value', 1, ...
        'Min', 0, ...
        'Max', 1, ...
        'Tag', 'RiskPlotListbox', ...
        'Interruptible', 'off', ...
        'BusyAction', 'queue', ...
        'Callback', @riskPlotSelectionChanged);
    thresholdLabel = uicontrol(fig, ...
        'Style', 'text', ...
        'String', 'Threshold', ...
        'HorizontalAlignment', 'left', ...
        'Tag', 'RiskThresholdLabel');
    thresholdEdit = uicontrol(fig, ...
        'Style', 'edit', ...
        'String', thresholdText, ...
        'Tag', 'RiskThresholdEdit', ...
        'Callback', @riskThresholdChanged);
    thresholdSlider = uicontrol(fig, ...
        'Style', 'slider', ...
        'Min', 0, ...
        'Max', 1, ...
        'Value', thresholdSliderValue, ...
        'SliderStep', [0.01 0.10], ...
        'Tag', 'RiskThresholdSlider', ...
        'Callback', @riskThresholdChanged);
    thresholdCount = uicontrol(fig, ...
        'Style', 'text', ...
        'String', '', ...
        'HorizontalAlignment', 'left', ...
        'Tag', 'RiskThresholdCount');
    stopButton = uicontrol(fig, ...
        'Style', 'pushbutton', ...
        'String', 'Stop monitor', ...
        'Tag', 'RiskStopButton', ...
        'TooltipString', 'Stop real-time monitoring', ...
        'Callback', @riskStopMonitoring);
    resetButton = uicontrol(fig, ...
        'Style', 'pushbutton', ...
        'String', 'Reset', ...
        'Tag', 'RiskResetButton', ...
        'TooltipString', 'Reset real-time monitoring to the initial stage', ...
        'Callback', @riskResetMonitoring);
    plotState = struct( ...
        'Axes', ax, ...
        'Risks', Risks, ...
        'UsersNames', usersNames, ...
        'ObjectsNames', objectsNames, ...
        'RiskThreshold', defaultRiskThreshold, ...
        'PreferredVisibleUserIdx', preferredVisibleUserIdx, ...
        'VisibleUserIndexes', (1:numel(usersNames))');
    setappdata(fig, 'RiskPlotState', plotState);
    setappdata(fig, 'RiskPlotAxes', ax);
    setappdata(fig, 'RiskPlotListbox', lb);
    setappdata(fig, 'RiskThresholdLabel', thresholdLabel);
    setappdata(fig, 'RiskThresholdEdit', thresholdEdit);
    setappdata(fig, 'RiskThresholdSlider', thresholdSlider);
    setappdata(fig, 'RiskThresholdCount', thresholdCount);
    setappdata(fig, 'RiskStopButton', stopButton);
    setappdata(fig, 'RiskResetButton', resetButton);
    setappdata(fig, 'RiskPlotLastValue', get(lb, 'Value'));
    set(fig, 'WindowButtonUpFcn', @(src, ~) riskPlotPollSelection(src));
    set(fig, 'SizeChangedFcn', @(src, ~) riskGuiLayout(src));
    set(fig, 'CloseRequestFcn', @riskPlotClose);

    pollTimer = timer('ExecutionMode', 'fixedSpacing', ...
        'Period', 0.35, ...
        'BusyMode', 'drop', ...
        'Name', 'RiskPlotSelectionPoll', ...
        'TimerFcn', @(~, ~) riskPlotPollSelection(fig));
    setappdata(fig, 'RiskPlotTimer', pollTimer);
    start(pollTimer);
    
    % Initial plot
    riskGuiLayout(fig);
    viewState = riskGuiApplyThreshold(fig);
    updatePlot(lb, [], ax, viewState.Risks, viewState.UsersNames, viewState.ObjectsNames, viewState.RiskThreshold);
    riskGuiLayout(fig);
    keepListboxVisible(lb);
end

function [threshold, sliderValue, thresholdText] = normalizeDefaultRiskThreshold(threshold)
    if isnumeric(threshold) && isscalar(threshold) && isnan(threshold)
        sliderValue = 0;
        thresholdText = 'off';
        return;
    end

    threshold = max(0, min(1, double(threshold)));
    sliderValue = threshold;
    thresholdText = sprintf('%.2f', threshold);
end

function keepListboxVisible(lb)
    try
        uistack(lb, 'top');
    catch
    end
end
