apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acram-data
  labels:
    app.kubernetes.io/name: acram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
